SELECT USER_ID, USERNAME, CREATED
FROM USER_USERS;

SELECT *
FROM USER_TABLES
ORDER BY TABLE_NAME;

SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'ORDERS'
ORDER BY COLUMN_ID;

SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'PRODUCTLIST'
ORDER BY COLUMN_ID;

SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'REVIEWS'
ORDER BY COLUMN_ID;

SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'STOREFRONT'
ORDER BY COLUMN_ID;

SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'USERLIBRARY'
ORDER BY COLUMN_ID;

SELECT *
FROM ORDERS 
ORDER BY PURCHASEDATE, ORDERID; 

SELECT *
FROM PRODUCTLIST
ORDER BY PRODUCTCODE;

SELECT *
FROM REVIEWS 
ORDER BY PRODUCTCODE; 

ORDER BY PRODUCTCODE, PRICE; 

ORDER BY PRODUCTCODE, PRICE; 

SELECT *
FROM USERLIBRARY 
ORDER BY USERID, PRODUCTCODE; 

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS
FROM USER_CONSTRAINTS 
ORDER BY TABLE_NAME, CONSTRAINT_NAME; 

SELECT USERNAME 
FROM USERBASE 
ORDER BY USERNAME ASC; 

SELECT VIEW_NAME
FROM USER_VIEWS
ORDER BY VIEW_NAME;

SELECT USERNAME, BIRTHDAY, WALLETFUNDS
FROM USERBASE
WHERE WALLETFUNDS < 25
ORDER BY WALLETFUNDS ASC, USERNAME; 

ORDER BY USERID, PRODUCTCODE; 
FROM USERLIBRARY
WHERE HOURSPLAYED > 100
ORDER BY USERID, PRODUCTCODE;

SELECT DISTINCT PRODUCTCODE
FROM USERLIBRARY
WHERE HOURSPLAYED < 10
ORDER BY PRODUCTCODE; 

SELECT SUM(PRICE) AS TOTALREVENUE
FROM ORDERS;

SELECT USERNAME, WALLETFUNDS
FROM USERBASE
WHERE WALLETFUNDS > 100;

SELECT USERNAME, LASTNAME, BIRTHDAY
FROM USERBASE
WHERE BIRTHDAY = (SELECT MIN(BIRTHDAY)
FROM USERBASE);

SELECT USERID, COUNT(PRODUCTCODE) AS TOTALGAMES
FROM USERLIBRARY
GROUP BY USERID;

SELECT PRODUCTNAME, RELEASEDATE
FROM PRODUCTLIST
WHERE RELEASEDATE < TO_DATE('01-JAN-2016', 'DD-MON-YYYY');

SELECT GENRE, COUNT(*) AS TOTALGAMES
FROM PRODUCTLIST
GROUP BY GENRE
ORDER BY TOTALGAMES DESC;

SELECT PRODUCTCODE
FROM STOREFRONT
WHERE LENGTH(DESCRIPTION) > 50;

SELECT u.USERNAME, p.PRODUCTNAME, PRICE, o.PURCHASEDATE
FROM USERBASE u
JOIN ORDERS  o ON u.USERID = o.USERID
JOIN PRODUCTLIST p ON o.PRODUCTCODE = p.PRODUCTCODE;

SELECT PRODUCTNAME
FROM PRODUCTLIST
WHERE PUBLISHER = 'RUBY WOLF';

SELECT p.PRODUCTNAME, AVG(r.RATING) AS AVGRATING
FROM PRODUCTLIST p
JOIN REVIEWS r ON p.PRODUCTCODE = r.PRODUCTCODE
GROUP BY p.PRODUCTNAME;

SELECT GENRE, COUNT(*) AS TOTALGAMES
FROM PRODUCTLIST
GROUP BY GENRE
ORDER BY TOTALGAMES DESC;

SELECT PRODUCTCODE
FROM STOREFRONT
WHERE LENGTH(DESCRIPTION) > 50;

SELECT u.USERNAME, p.PRODUCTNAME, PRICE, o.PURCHASEDATE
FROM USERBASE u
JOIN ORDERS  o ON u.USERID = o.USERID
JOIN PRODUCTLIST p ON o.PRODUCTCODE = p.PRODUCTCODE;

SELECT PRODUCTNAME
FROM PRODUCTLIST
WHERE PUBLISHER = 'RUBY WOLF';

















  




 
 
 

 
 






  



